# sonar-project.properties
sonar.projectKey=Python
sonar.projectName=Python
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8

# Optional: Exclude tests or venvs
sonar.exclusions=**/__pycache__/**,**/venv/**

# Optional: For coverage reports
# sonar.python.coverage.reportPaths=coverage.xml
